### ISSUE TITLE
Cannot find module '../dist/CDVAutomator.js'

### ISSUE THREAD

**Issue by dariosalviwork** [Urucas/cordova-test#15]
On a MacOS, installed with `sudo npm install -g cordova-test`, after I run: `cordova-test` and it says:

```
Error: Cannot find module '../dist/CDVAutomator.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova-test/bin/cli:19:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

**Comment by dariosalviwork** [comment]
I think the problem is in bin/cli,  where it says `require('../dist/CDVAutomator.js'),`

**Comment by dariosalviwork** [comment]
should be the same cause as #16
