### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by dariosalviwork** [Urucas/cordova-test#16]
After having fixed the bug about ../dist myself, now I am facing this one:

```
/usr/local/lib/node_modules/cordova-test/lib/CDVAutomator.js:1
(function (exports, require, module, __filename, __dirname) { import logger from './CDVLogger.js';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova-test/bin/cli:19:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

run on node v 5.10.1

**Comment by dariosalviwork** [comment]
also tried on more recent node v6.3.1, "import" is no recognised

**Comment by vrunoa** [comment]
hey @dariosalviwork can you go inside `/usr/local/lib/node_modules/cordova-test` and run `npm run build` I believe it's not transpiling correctly. I'll try to fix this on the weekend and let you know.

**Comment by dariosalviwork** [comment]
that solved it, no syntax errors now!

**Comment by vrunoa** [comment]
cool @dariosalviwork! I believe it's not publishing the correct code to `npm`. I have to do some refactor, hope to fix this on a new release.

**Comment by ndevendh** [comment]
@vrunoa 
I tried to fix the issue by running below command. But im getting error "The syntax of the command is incorrect."

`
C:\Users\xxxxx\AppData\Roaming\npm\node_modules\cordova-test>npm run build

> cordova-test@0.1.6 build C:\Users\xxxxx\AppData\Roaming\npm\node_modules\cord
ova-test
> npm run clean && babel ./lib --out-dir ./dist && mkdir ./dist/caps && cp ./lib
/caps/* ./dist/caps


> cordova-test@0.1.6 clean C:\Users\xxxx\AppData\Roaming\npm\node_modules\cord
ova-test
> rimraf dist

lib\CDVAutomator.js -> dist\CDVAutomator.js
lib\CDVLogger.js -> dist\CDVLogger.js
lib\CDVTest.js -> dist\CDVTest.js
lib\CDVTestLocal.js -> dist\CDVTestLocal.js
lib\CDVTestSauce.js -> dist\CDVTestSauce.js
lib\CDVTestTestdroid.js -> dist\CDVTestTestdroid.js
lib\paramsParser.js -> dist\paramsParser.js
The syntax of the command is incorrect.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! cordova-test@0.1.6 build: `npm run clean && babel ./lib --out-dir ./dis
t && mkdir ./dist/caps && cp ./lib/caps/* ./dist/caps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cordova-test@0.1.6 build script 'npm run clean && babel .
/lib --out-dir ./dist && mkdir ./dist/caps && cp ./lib/caps/* ./dist/caps'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cordova-test package,

npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && babel ./lib --out-dir ./dist && mkdir ./dist/caps
&& cp ./lib/caps/* ./dist/caps
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cordova-test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cordova-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\xxxx\AppData\Roaming\npm\node_modules\cordova-test\npm-d
ebug.log
`
Im using node version 6.9.2. Please provide a solution to fix this issue

Please provide a solution
