### ISSUE TITLE
Example code fails to compile

### ISSUE THREAD

**Issue by okobloko** [Urucas/cordova-test#21]
cordova-test android tests/mocha --babel  -Xlint

It complains about async -we've tried running it with and without babel.

babel-core@6.25.0

Any clues?

✓ Parsing cli params
{"platform":"android","platform_path":"/Users/XXXXX/WORK/WORKSPACES-Programming/CordovaSpikes/example/platforms/android","tests_path":"/Users/XXXXX/WORK/WORKSPACES-Programming/CordovaSpikes/example/tests/mocha","compile":true,"babel":true,"teamcity":false,"device":false,"env":"mocha","env_files":"*.js","device_name":"Android Emulator","isLocal":true}

✓ Checking selected platform is supported
ANDROID 

✓ Checking test(s) path exists
✓ Cordova installed, cordova version: 7.0.1

✓ Getting cordova project info
Project name: TestExample
Package name: com.sefol.testexample

Compiling cordova application, this may take a while!
✓ Cordova project buildd
✓ Checking compiled application exists
✓ Checking appium is installed
Appium installed, appium version: 1.6.5

{"deviceName":"Android Emulator","platformName":"Android","app":"/Users/XXXXX/WORK/WORKSPACES-Programming/CordovaSpikes/example/platforms/android/build/outputs/apk/android-debug.apk","app-package":"com.sefol.testexample","host":"127.0.0.1","port":4723}
✓ Platform capabilities updated
Running test; mocha /Users/XXXXX/WORK/WORKSPACES-Programming/CordovaSpikes/example/tests/mocha/1_index_test.js --platform android
/Users/XXXXX/WORK/WORKSPACES-Programming/CordovaSpikes/example/tests/mocha/1_index_test.js:26
    it("should show hello world", async function (done) {
                                  ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at loader (/Users/XXXXX/.nvm/versions/node/v7.1.0/lib/node_modules/babel-core/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/XXXXX/.nvm/versions/node/v7.1.0/lib/node_modules/babel-core/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /Users/XXXXX/.nvm/versions/node/v7.1.0/lib/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/XXXXX/.nvm/versions/node/v7.1.0/lib/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/XXXXX/.nvm/versions/node/v7.1.0/lib/node_modules/mocha/lib/mocha.js:513:10)
    at Object.<anonymous> (/Users/XXXXX/.nvm/versions/node/v7.1.0/lib/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
Test finished

Running test; mocha /Users/XXXXX/WORK/WORKSPACES-Programming/CordovaSpikes/example/tests/mocha/2_button_test.js --platform android
/Users/XXXXX/WORK/WORKSPACES-Programming/CordovaSpikes/example/tests/mocha/2_button_test.js:26
    it("should click a button", async function (done) {
                                ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at loader (/Users/XXXXX/.nvm/versions/node/v7.1.0/lib/node_modules/babel-core/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/XXXXX/.nvm/versions/node/v7.1.0/lib/node_modules/babel-core/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /Users/XXXXX/.nvm/versions/node/v7.1.0/lib/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/XXXXX/.nvm/versions/node/v7.1.0/lib/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/XXXXX/.nvm/versions/node/v7.1.0/lib/node_modules/mocha/lib/mocha.js:513:10)
    at Object.<anonymous> (/Users/XXXXX/.nvm/versions/node/v7.1.0/lib/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
Test finished

✓ All test finished!

**Comment by vrunoa** [comment]
@okobloko i'll try to take a look later tonight

**Comment by okobloko** [comment]
Fantastic!
